# Generated by Django 6.0.3 on 2026-03-09 20:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 9, 20, 30, 23, 439197)
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="players",
                to="db.guild",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="db.race",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="db.race",
            ),
        ),
    ]
