# Generated by Django 6.0.3 on 2026-03-09 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_player_created_at_alter_player_guild_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="player",
            name="nickname",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
