# Generated by Django 6.0.3 on 2026-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_alter_player_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="nickname",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
